language: objective-c
script:
  - xctool -workspace dojo-testing.xcworkspace -scheme dojo-testing -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace dojo-testing.xcworkspace -scheme dojo-testingTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
